### PR TITLE
Add exclude_objects parameter (#1)

### PR DESCRIPTION
**Pull request by Vaigard**
Setting up the role model can be redundant for cases where you need to exclude a couple of objects from the audit (for example, some temporary or service tables).

I suggest using a simple optional configuration parameter pgaudit.exclude_objects for such cases.

### CODE REVIEW

**Comment by dwsteele** [comment]
If anything I think we'd want `pgaudit_role_exclude`, but I'm not sure I'm too excited about that either. It'd be easy for new objects to appear and start cluttering up the logs.

**Comment by Vaigard** [comment]
My case where this change came from is the elimination of a large cache table that is regularly updated in its entirety. New objects can be added, but only under specific conditions, and if the schema is fixed, the administrator always knows which objects to exclude.

**Comment by bmistry13** [comment]
@Vaigard  and @dwsteele , 

We need this functionality as well and I am sure others wanted this exclude functionality.  
The problem is that pgAudit does not provide masking capability per column on the Audit log.  so I have to exclude all logging-sensitive tables in the audit log in plain text. eg. acess_token/username/email/SSN etc I have tried pg_anonymize it does not work with pg_audit (but works on psql client).  So, I wanted to exclude specific tables certain sensitive tables, and logs REST.  We are a federal customer that requires AUDIT compliance but sensitive data must masked.  There is no easy way to do this with pgAudit.  Is there any way you can adopt from pg_anonymize or exclude specific tables?    This is needed. 

If you have any alternative way, please let me know.  We are looking for a solution NOT to log sensitive tables. Any solution will be greatly appreciated.


Thanks,

BHavesh

**Comment by Vaigard** [comment]
Hi! Any updates?

**Comment by dwsteele** [comment]
@Vaigard As I said above, if we were to do this I would prefer a `pgaudit_role_exclude` role rather than a list of objects in a field, which could grow very large. I'm not planning to implement `pgaudit_role_exclude` but I would consider the patch if it were submitted.

**Pull request closed without merging**
