### PR TITLE
Improve description for pgaudit.log_rows setting.

### PR DESCRIPTION
**Pull request by sbimochan**
While reading it gives a sense that it will provides us the rows affected but actually it only gives the number of rows affected.

### CODE REVIEW

**Comment by dwsteele** [comment]
I agree with this change in general, but I think "number of rows" reads strangely in the second sentence. We could either drop it:
```
Specifies that audit logging should include the number of rows retrieved or affected by a statement. When enabled the rows field will be included after the parameter field.
```
Or use row count instead:
```
Specifies that audit logging should include the row count retrieved or affected by a statement. When enabled the number of row count field will be included after the parameter field.
```

**Comment by sbimochan** [comment]
Hey @dwsteele , here are some updates, I've added few standard line gaps needed in markdown files as well. Let me know if you dislike the changes.

**Comment by dwsteele** [comment]
I'm not sure what all these other changes are for but I don't have time to review them. Please revert all but the description change in 254cc24.

**Comment by sbimochan** [comment]
@dwsteele I've reverted them

**Review by dwsteele — APPROVED** [review]
Thanks, this looks good now.

**Pull request merged**
