### PR TITLE
Add log_parameter_max_size to set maximum size of logged parameters.

### PR DESCRIPTION
**Pull request by Xof**
This WIP PR addresses issue #186. It adds a new GUC, `pgaudit.max_object_size` (bikeshedding on name welcome). If non-zero, any parameter value whose storage representation is longer in bytes than that value is replaced by a placeholder, `<long field suppressed>`.  We use the storage format rather than (say) number of characters to avoid having to pull in, potentially decompress and character-encode or scan the value just to throw it away.

This PR doesn't contain test or doc fixes; those will be added once the code seems reasonable.

### CODE REVIEW

**Review by dwsteele — CHANGES_REQUESTED** [review]
I have some edits but I am unable to push them. Can you make sure this branch can be edited by maintainers?

The patch overall looks reasonable to me. A few things:

**Comment by Xof** [comment]
Apparently, GitHub won't let you allow a PR to be edited by upstream maintainers if the fork is under an organization instead of an individual. Instead, I've added you as a maintainer to the fork.

1. My thought here is that it isn't worth the overhead of de-TOASTing the value just to show the first few bytes.
2. That sounds great for the GUC name.

**Comment by dwsteele** [comment]
> Instead, I've added you as a maintainer to the fork.

**Comment by Xof** [comment]
Documentation and tests updated. Thanks!

**Review by dwsteele — APPROVED** [review]
Pushed up my last edits. I believe this is ready to commit if you are OK with my changes.

**Comment by Xof** [comment]
LGTM!

**Pull request merged**
