### PR TITLE
Suppress logging for internally generated foreign-key queries.

### PR DESCRIPTION
**Pull request by petere**
When auditing write operations (pgaudit.log = 'write'), we check
whether the query requires ACL_UPDATE permissions.  This also catches
SELECT FOR UPDATE, SELECT FOR KEY SHARE, etc. queries, because there
is no separate permission for those.  This is especially annoying
because internally generated foreign-key queries get logged. (see #80)

To avoid this, in PostgreSQL 13 we can also check the rellockmode
field of the range table entry.  If it's at least RowExclusiveLock,
then it's a real UPDATE, else it's some kind of SELECT with locking
clause.

(This might need some `#ifdef`s or something like that, since it's PG13 only, but let's discuss the general idea first.)

### CODE REVIEW

**Comment by dwsteele** [comment]
Well, that's certainly better than what we have now.  I'm only worried that it could be a bit fragile because we are piggy-backing on functionality not really intended for this use (which is pretty much the story of pgaudit's life anyway).  Of course, proper regression tests will help with this.

Speaking with some colleagues we were thinking it should be possible for Postgres to mark queries that were internally generated.  Perhaps as an eflag on ExecutorStart?

Of course, that would likely need to be PG14 work unless it is super-trivial, but it might be a better technique to use in the future.

**Comment by simonat2ndQuadrant** [comment]
Peter's proposal is insightful and accurate. I'm not sure that having a boolean to say "internally generated" is going to help much here since that could be abused by someone. Looking at the lock level does the right thing.

**Comment by petere** [comment]
> Speaking with some colleagues we were thinking it should be possible for Postgres to mark queries that were internally generated. Perhaps as an eflag on ExecutorStart?

There are two overlapping distinctions here:

1. internally generated queries vs. others
2. UPDATE vs. SELECT FOR UPDATE

My change attempts to address the second one, namely that we don't want to log SELECT FOR UPDATE (and similar) as "data modification". This applies whether the command is internally generated or not.

**Comment by dwsteele** [comment]
> My change attempts to address the second one, namely that we don't want to log SELECT FOR UPDATE (and similar) as "data modification". This applies whether the command is internally generated or not.

Well, it does have that advantage. For the moment we have no better solution so this will be a welcome improvement for PG13.

> This might need some #ifdefs or something like that, since it's PG13 only...

We maintain one branch per version of Postgres (just as Postgres does). We are planning to make the master branch support all versions and keep the release branches for users who want very stable versions but we have not done that yet, so a PG13-only version for master is fine.

So, I think this looks commit-able once tests have been added.

**Comment by dwsteele** [comment]
Since no tests seemed to be forthcoming I went ahead and did that myself. Luckily, we already had a good test that just needed to be modified a bit to excercise this code.

The logic wasn't quite right. As written it just audit logged the update as a select instead which didn't seem like much of an improvement. I modified the logic and pushed it further up so it doesn't interfere with session logging, which only happens on the first RTE. I don't see SELECT FOR UPDATE appearing first in the rte list but that doesn't mean it can't happen, or something like it.

**Comment by dwsteele** [comment]
If there are no objections I'll merge this tomorrow so I can push on the beta tag.

**Review by dwsteele — APPROVED** [review]

**Pull request merged**
